---

- name: Create Users, Install Docker, Deploy Stack
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo

  roles:
      - base
      - docker
      - users
      - certbot
        # - ghost-stack
