version: "3"

services:
  ghost:
    image: ghost:latest
    container_name: tux-sudo-ghost
    environment:
      - NODE_ENV=production
    volumes:
      - ghost-data:/var/lib/ghost
    networks:
      - ghost

  proxy:
    image: nginx:latest
    container_name: nginx-rev-proxy
    links:
      - ghost
    networks:
      - ghost
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx-default:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/ssl

networks:
  ghost:

volumes:
  ghost-data:
