---

- name: Create App directory
  file:
    path: /var/lib/tux-sudo
    state: directory
    mode: 0755

- name: Add stack config to instance
  copy:
    src: files/docker-compose.yml
    dest: /var/lib/tux-sudo/docker-compose.yml
    owner: ghost
    mode: 0644

- name: Add config files
  copy:
    src: files/config
    dest: /var/lib/tux-sudo

- name: Bring Up Docker Services
  command: docker-compose up -d
  async: 1800
  poll: 5
  args:
    chdir: /var/lib/tux-sudo

- name: Inject ghost-config
  command: docker cp /var/lib/tux-sudo/config/config.js tux-sudo-ghost:/var/lib/ghost/config.js

- name: Restart ghost stack
  command: docker-compose restart 
  async: 1800
  poll: 5
  args:
    chdir: /var/lib/tux-sudo
